name: readme-lhs
version: '0.1.1'
synopsis: See readme.md
description: See readme.md for description.
category: Development
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: 2016 Tony Day
license: BSD3
github: tonyday567/readme-lhs
extra-source-files:
- readme.md
- index.html
- stack.yaml
- other/readme-lhs.hsfiles
- other/readme-hs.hsfiles
default-extensions:
- NoImplicitPrelude
- UnicodeSyntax
- BangPatterns
- BinaryLiterals
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DisambiguateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NegativeLiterals
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- TupleSections
- TypeFamilies
- TypeOperators
- ExtendedDefaultRules
dependencies:
- base >=4.7 && <5
- protolude
executables:
  readme-lhs-example:
    main: example.lhs
    source-dirs: example
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-generic
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - tasty
    - doctest
