resolver: nightly-2021-02-12

extra-deps:
  - numhask-0.7.1.0
  - random-1.2.0

  # pandoc
  - pandoc-2.11.2
  - citeproc-0.2
  - commonmark-0.1.1.2
  - commonmark-extensions-0.2.0.4
  - commonmark-pandoc-0.2.0.1

allow-newer: true
